--
-- Moving from MySQLto the Galera cluster requires primary keys.
--
--
ALTER TABLE access_token_permissions ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE approved_site_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE authentication_holder_authority ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE authentication_holder_extension ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE authentication_holder_request_parameter ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE authentication_holder_resource_id ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE authentication_holder_response_type ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE authentication_holder_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE claim_issuer ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE claim_token_format ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE claim_to_permission_ticket ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE claim_to_policy ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_authority ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_claims_redirect_uri ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_contact ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_default_acr_value ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_grant_type ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_post_logout_redirect_uri ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_redirect_uri ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_request_uri ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_resource ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_response_type ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE client_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE permission_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE policy_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE resource_set_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE saved_user_auth_authority ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE token_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE user_edu_person_affiliation ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE user_edu_person_entitlement ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE user_edu_person_scoped_affiliation ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE user_is_member_of ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE user_schac_personal_unique_code ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE user_uid ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE whitelisted_site_scope ADD id MEDIUMINT PRIMARY KEY AUTO_INCREMENT;